belazy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('siteuser.urls')),
    path('pic/', include('picture.urls'))
]

picture/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from picture import views


app_name = 'picture'
urlpatterns = [
    path('', views.ImgList.as_view(), name='images'),
    path('publish/', views.get_publication_img, name='publish'),
    path('vote/', views.pic_vote),
]

siteuser/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from siteuser import views

app_name = 'siteuser'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password/', views.change_password, name='changepwd'),
]

picture/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class PictureEntry(models.Model):
    uploader = models.ForeignKey('siteuser.User', on_delete=models.CASCADE)
    # img_file = models.ImageField(upload_to='')
    img_url = models.URLField(max_length=300)
    description = models.CharField(max_length=500, null=True, blank=True)
    pub_time = models.DateTimeField(default=timezone.now)
    positive = models.IntegerField(default=0)
    negative = models.IntegerField(default=0)
    checked = models.BooleanField(default=False)

    def __str__(self):
        return str(self.pk)

    # @property
    # def positive(self):
    #     return PicVoteLog.objects.filter(pic=self.pk, type=1).count()

    # @property
    # def negative(self):
    #     return PicVoteLog.objects.filter(pic=self.pk, type=0).count()

    def totaly_bad(self):
        if self.negative > 3 * self.positive:
            return True


class PicVoteLog(models.Model):
    pic = models.ForeignKey(PictureEntry, on_delete=models.CASCADE)
    src = models.CharField(max_length=50, null=True)
    type = models.IntegerField()

picture/forms.py
from django.forms import ModelForm, Textarea
from picture.models import PictureEntry


class PublishImgForm(ModelForm):

    class Meta:
        model = PictureEntry
        fields = ['img_url', 'description']
        widgets = {
            'img_url': Textarea(attrs={'cols': 50, 'rows': 10}),
            'description': Textarea(attrs={'cols': 50, 'rows': 20}),
        }

picture/views.py
from datetime import timedelta
from django.shortcuts import redirect
from django.http import JsonResponse
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.decorators.http import require_POST
from django.utils import timezone
# from django.db.models import F
from picture.forms import PublishImgForm
from picture.models import PictureEntry


# Create your views here.


def list_limit_time():
    return timezone.localdate() - timedelta(days=30)


class ImgList(ListView):
    template_name = 'picture/img_list.html'
    queryset = PictureEntry.objects.select_related('uploader').filter(
        checked=True, pub_time__date__gt=list_limit_time()
    ).order_by('-pub_time')

    paginate_by = 10
    context_object_name = 'entry_list'
    extra_context = {
        'form': PublishImgForm(),
    }

    def get_context_data(self, *, object_list=None, **kwargs):
        content = super().get_context_data(**kwargs)
        if not content['is_paginated']:
            content['front'] = []
            content['back'] = []
            return content

        paginator = content['paginator']
        cur_page = content['page_obj']
        cur_num = cur_page.number
        if paginator.num_pages <= 13:
            front_pages = list(range(1, cur_num))
            back_pages = list(range(cur_num+1, paginator.num_pages+1))
        else:
            if cur_num-1 <= 6:
                front_pages = list(range(1, cur_num))
            else:
                front_pages = [1, '...', cur_num-4, cur_num-3, cur_num-2, cur_num-1]

            if paginator.num_pages-cur_num > 11:
                back_pages = [cur_num+1, cur_num+2, cur_num+3, cur_num+4, '...', paginator.num_pages]
            else:
                back_pages = list(range(cur_num+1, paginator.num_pages+1))

        content['front'] = front_pages
        content['back'] = back_pages

        return content


@require_POST
@login_required(redirect_field_name=None, login_url=reverse_lazy('siteuser:login'))
def get_publication_img(request):
    new_pub_form = PublishImgForm(request.POST)
    if new_pub_form.is_valid():
        request.user.pictureentry_set.create(
            img_url=new_pub_form.cleaned_data['img_url'],
            description=new_pub_form.cleaned_data['description'],
        )
    # return JsonResponse({'status': 'ok'})
    return redirect(reverse('picture:images'))


@require_POST
def pic_vote(request):
    if request.user.is_authenticated:
        voter = str(request.user.pk)
    else:
        voter = request.META.get('REMOTE_ADDR')
        # ip = request.META.get('HTTP_X_FORWARDED_FOR')
    vtype = 0
    if request.POST['type'] == 'pos':
        vtype = 1

    try:
        # pic_id = int(request.POST['pic'])
        pic_obj = PictureEntry.objects.get(id=int(request.POST['pic']))
    except ValueError:
        return JsonResponse({'status': 'some error'})
    except PictureEntry.DoesNotExist:
        return JsonResponse({'status': 'some error'})

    if pic_obj.picvotelog_set.filter(src=voter).exists():
        return JsonResponse({'status': '已投过票'}, json_dumps_params={
            'ensure_ascii': False
        })
    else:
        pic_obj.picvotelog_set.create(src=voter, type=vtype)
        if vtype:
            # PictureEntry.objects.filter(id=pic_id).update(positive=F('positive') + 1)
            pic_obj.positive += 1
        else:
            # PictureEntry.objects.filter(id=pic_id).update(negative=F('negative') + 1)
            pic_obj.negative += 1
        pic_obj.save()

        return JsonResponse({'status': 'ok'})

picture/templates/picture/img_list.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>骚图</title>
    {% load static %}
    <!--<script src="https://code.jquery.com/jquery-3.3.1.js"></script>-->
    <script src="{% static 'picture/js/jquery-3.3.1.js' %}"></script>
</head>
<body>
    <div>
        <a href="{% url 'siteuser:logout' %}">注销登陆</a>
    </div>

<div>
    <ul style="list-style-type: none;">
    {% for entry in entry_list %}
    <li>
        <div>
            <span>{{ entry.uploader.username }}</span>
            <span>{{ entry.id }}</span>
            <div>
                <img src="{{ entry.img_url}}">
            </div>
            <p>
                {{ entry.description }}
            </p>
            <div>
                <a class="vote" href="javascript:;" data-id="{{ entry.id }}" data-type="pos">↑</a>
                <span> {{ entry.positive }} </span>
                <a class="vote" href="javascript:;" data-id="{{ entry.id }}" data-type="neg">↓</a>
                <span> {{ entry.negative }} </span>
            </div>
        </div>
    </li>
    {% empty %}
        <span> no content </span>
    {% endfor %}
    </ul>
</div>

<div>
    {% if is_paginatedc%}
        <ul style="list-style-type:none">
            <li><div><a href="?page={{ front|last }}"> 上一页 </a></div></li>
            {% for p in front %}
                {% if p == '...' %}
                    <li><div><span> {{ p }} </span></div></li>
                {% else %}
                    <li><div><a href="?page={{ p }}"> {{ p }} </a></div></li>
                {% endif %}
            {% endfor %}
            <li><div><a class="active" href="?page={{ page_obj.number }}"> {{ page_obj.number }} </a></div></li>
            {% for p in back %}
                {% if p == '...' %}
                    <li><div><span> {{ p }} </span></div></li>
                {% else %}
                    <li><div><a href="?page={{ p }}"> {{ p }} </a></div></li>
                {% endif %}
            {% endfor %}
            <li><div><a href="?page={{ back|first }}"> 下一页 </a></div></li>
        </ul>
    {% endif %}
</div>

<div id="message" style=" display: none;"></div>

<div>
    <form id="publishform" action="{% url 'picture:publish' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="{{ form.img_url.id_for_label }}">粘贴图片链接</label>
            {{ form.img_url }}
        </div>
        <div>
            <label for="{{ form.description.id_for_label }}">添加备注</label>
            {{ form.description }}
        </div>
        <!--<input type="button" onclick="submitForm();" value="点击发布">-->
        <input type="submit" value="点击发布">
    </form>
</div>

<script>
    var token = $(" input[name='csrfmiddlewaretoken'] ").val();

    function submitForm(){
        <!--var token = $.cookie("csrftoken");-->
        var to_url = $(" #publishform ").attr("action");
        var vurl = $(" #id_img_url ").val();
        var vdes = $(" #id_description").val();

        $.ajax({
            url: to_url,
            type: "POST",
            headers:{"X-CSRFToken": token},
            data: {
                img_url: vurl,
                description: vdes,
            },
        });
    }

    $(document).ready(function(){
        $(".vote").click(function () {
            var v_id = $(this).attr("data-id");
            var type = $(this).attr("data-type");
            $.ajax({
                url: "vote/",
                type: "POST",
                data: {
                    pic: v_id,
                    type: type,
                },
                headers:{"X-CSRFToken": token},
                success: function(data){
                    var msg = data["status"];
                    if(msg=="ok"){
                        var t = parseInt($(this).next().html());
                        $(this).next().html(t+1);
                    }
                    else{
                        $(" #message ").html(msg);
                        $(" #message ").show().delay(1000).hide(200);
                    }
                }
            });
        });
    })
</script>
</body>
</html>