belazy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('siteuser.urls')),
    path('pic/', include('picture.urls'))
]

siteuser/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from siteuser import views

app_name = 'siteuser'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('password/', views.change_password, name='changepwd'),
]

siteuser/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

# Create your models here.


class SiteUserManager(BaseUserManager):

    def create_user(self, username, password=None, **extra_fields):
        if not username:
            raise ValueError('The given username must be set')
        username = self.model.normalize_username(username)

        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    """
    password username email date_joined
    不做激活处理，email不做强制。
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        # primary_key=True,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email address'), blank=True, null=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'

    objects = SiteUserManager()

siteuser/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from siteuser.models import User as SiteUser


# 参考自带表单设计，用于自定义网站用户model
class AuthSiteUserForm(AuthenticationForm):
    """
    登录验证表单，包括 username, password
    """
    pass


class SiteUserCreationForm(UserCreationForm):
    """
    注册账户，基于model User，包括 username, email, password1, password2
    其中，email非必需
    """

    class Meta(UserCreationForm.Meta):
        model = SiteUser
        fields = ['username', 'email']


class UserPasswdChangeForm(PasswordChangeForm):
    pass
    # label_suffix = ''

siteuser/views.py
from urllib.parse import urlparse

from django.http import QueryDict
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from siteuser.forms import *

# Create your views here.

_index = 'picture:images'


def register(request):
    if request.method == 'POST':
        new_user_form = SiteUserCreationForm(request.POST, label_suffix='')
        if new_user_form.is_valid():
            new_user_form.save()

            reged_user = authenticate(
                username=new_user_form.cleaned_data['username'],
                password=new_user_form.cleaned_data['password1'],
            )
            login(request, reged_user)

            return redirect(reverse(_index))

    else:
        new_user_form = SiteUserCreationForm(label_suffix='')

    return render(request, template_name='siteuser/register.html', context={
        'form': new_user_form
    })


def login_user(request):
    if request.method == 'POST':
        # username = request.POST['username']
        # password = request.POST['password']
        # logining_user = authenticate(request, username=username, password=password)

        auth_form = AuthSiteUserForm(request, data=request.POST, label_suffix='')
        if auth_form.is_valid():
            # 验证数据合法时，同时authenticate()验证返回对象实例
            logining_user = auth_form.get_user()
            if logining_user.is_authenticated:
                login(request, logining_user)

                qs = QueryDict(urlparse(request.get_full_path()).query, mutable=True)
                login_from = qs.get('next')
                if login_from:
                    return redirect(login_from)
                return redirect(reverse(_index))
            else:
                return redirect(reverse('siteuser:register'))

    else:
        auth_form = AuthSiteUserForm(label_suffix='')

    return render(request, 'siteuser/login_page.html', context={
         'form': auth_form,
    },)

# 第一次登录，cookie中只有csrf_token，验证系统中间件返回AnonymousUser。
# 后台登录动作login_view中，表单验证时验证后端通过账号密码获取用户对象。
# 之后，cookie中有sessionid，其实为用户主键。验证中间件循环所有验证后端，查询主键获取对象。


# @login_required(login_url=reverse_lazy('siteuser:login'))
def logout_user(request):
    logout(request)
    return redirect(reverse(_index))


@login_required(login_url=reverse_lazy('siteuser:login'))
def change_password(request):
    if request.method == 'POST':
        change_form = UserPasswdChangeForm(request.user, data=request.POST, label_suffix='')
        if change_form.is_valid():
            change_form.save()
            return redirect(reverse('siteuser:login'))

    else:
        change_form = UserPasswdChangeForm(request.user, label_suffix='')

    return render(request, template_name='siteuser/change_pwd.html', context={
        'form': change_form
    })


# def index(request):
#     handle_index = ImgList.as_view()
#     return handle_index(request)

siteuser/templates/siteuser/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
    <div>
        <form action="{% url 'siteuser:changepwd' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.label_tag }} {{ field }}
                    <!--{% if field.help_text %}-->
                    <!--<p class="help">{{ field.help_text|safe }}</p>-->
                    <!--{% endif %}-->
                    {{ field.errors }}
                </div>
            {% endfor %}

            {% if form.non_field_errors %}
                {{ form.non_field_errors }}
            {% endif %}
            <input type="submit" value="提交修改"/>
        </form>
    </div>
</body>
</html>

siteuser/templates/siteuser/login_page.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>用户登录</title>
</head>
<body>
    <div>
        <form action="{% url 'siteuser:login' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.label_tag }} {{ field }}
                    <!--{% if field.help_text %}-->
                    <!--<p class="help">{{ field.help_text|safe }}</p>-->
                    <!--{% endif %}-->
                    {{ field.errors }}
                </div>
            {% endfor %}

            {% if form.non_field_errors %}
            {{ form.non_field_errors }}
            {% endif %}
            <input type="submit" value="登录"/>
            <a href="{% url 'siteuser:register' %}"><label>新用户注册</label></a>
        </form>
    </div>

</body>
</html>

siteuser/templates/siteuser/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新用户注册</title>
</head>
<body>
    <div>
        <form action="{% url 'siteuser:register' %}" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.label_tag }} {{ field }}
                    <!--{% if field.help_text %}-->
                    <!--<p class="help">{{ field.help_text|safe }}</p>-->
                    <!--{% endif %}-->
                    {{ field.errors }}
                </div>
            {% endfor %}

            {% if form.non_field_errors %}
            {{ form.non_field_errors }}
            {% endif %}
            <input type="submit" value="注册"/>
        </form>
    </div>
</body>
</html>